# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import serving_pb2 as com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in com/cisco/wcc/ccai/v1/serving_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiInsightStub(object):
    """
    Service to subscribe to, to get AI Insights
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingInsightServing = channel.unary_stream(
                '/com.cisco.wcc.ccai.v1.AiInsight/StreamingInsightServing',
                request_serializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingRequest.SerializeToString,
                response_deserializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingResponse.FromString,
                _registered_method=True)
        self.InsightServing = channel.unary_unary(
                '/com.cisco.wcc.ccai.v1.AiInsight/InsightServing',
                request_serializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingRequest.SerializeToString,
                response_deserializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingResponse.FromString,
                _registered_method=True)


class AiInsightServicer(object):
    """
    Service to subscribe to, to get AI Insights
    """

    def StreamingInsightServing(self, request, context):
        """
        Server side Streaming gRPC Call that produces streaming insights
        for a given conversation ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsightServing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiInsightServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingInsightServing': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamingInsightServing,
                    request_deserializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingRequest.FromString,
                    response_serializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingResponse.SerializeToString,
            ),
            'InsightServing': grpc.unary_unary_rpc_method_handler(
                    servicer.InsightServing,
                    request_deserializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingRequest.FromString,
                    response_serializer=com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.cisco.wcc.ccai.v1.AiInsight', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.cisco.wcc.ccai.v1.AiInsight', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiInsight(object):
    """
    Service to subscribe to, to get AI Insights
    """

    @staticmethod
    def StreamingInsightServing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.cisco.wcc.ccai.v1.AiInsight/StreamingInsightServing',
            com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingRequest.SerializeToString,
            com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.StreamingInsightServingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsightServing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.cisco.wcc.ccai.v1.AiInsight/InsightServing',
            com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingRequest.SerializeToString,
            com_dot_cisco_dot_wcc_dot_ccai_dot_v1_dot_serving__pb2.InsightsServingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
