# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/cisco/wcc/ccai/v1/common/callinsights.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'com/cisco/wcc/ccai/v1/common/callinsights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/com/cisco/wcc/ccai/v1/common/callinsights.proto\x12\x15\x63om.cisco.wcc.ccai.v1\"f\n\x12\x43\x61llInsightsResult\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12?\n\x0f\x63\x61llInsightType\x18\x02 \x01(\x0e\x32&.com.cisco.wcc.ccai.v1.CallInsightType*I\n\x0f\x43\x61llInsightType\x12!\n\x1d\x43\x41LL_INSIGHT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fVA_CALL_SUMMARY\x10\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.cisco.wcc.ccai.v1.common.callinsights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CALLINSIGHTTYPE']._serialized_start=178
  _globals['_CALLINSIGHTTYPE']._serialized_end=251
  _globals['_CALLINSIGHTSRESULT']._serialized_start=74
  _globals['_CALLINSIGHTSRESULT']._serialized_end=176
# @@protoc_insertion_point(module_scope)
