# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/cisco/wcc/ccai/v1/common/suggestions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'com/cisco/wcc/ccai/v1/common/suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/cisco/wcc/ccai/v1/common/suggestions.proto\x12\x15\x63om.cisco.wcc.ccai.v1\"^\n\x11\x41gentAnswerResult\x12\x39\n\x0b\x61gentanswer\x18\x02 \x01(\x0b\x32\".com.cisco.wcc.ccai.v1.AgentAnswerH\x00\x42\x0e\n\x0c\x61nswer_oneof\"K\n\x0b\x41gentAnswer\x12.\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x1d.com.cisco.wcc.ccai.v1.Answer\x12\x0c\n\x04tags\x18\x02 \x03(\t\"\xa7\x02\n\x06\x41nswer\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x10\n\x08snippets\x18\x03 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x0e\n\x06source\x18\x06 \x01(\t\x12=\n\x08metadata\x18\x07 \x03(\x0b\x32+.com.cisco.wcc.ccai.v1.Answer.MetadataEntry\x12\x15\n\ranswer_record\x18\x08 \x01(\t\x12/\n\thighlight\x18\t \x03(\x0b\x32\x1c.com.cisco.wcc.ccai.v1.range\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"#\n\x05range\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.cisco.wcc.ccai.v1.common.suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSWER_METADATAENTRY']._loaded_options = None
  _globals['_ANSWER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AGENTANSWERRESULT']._serialized_start=73
  _globals['_AGENTANSWERRESULT']._serialized_end=167
  _globals['_AGENTANSWER']._serialized_start=169
  _globals['_AGENTANSWER']._serialized_end=244
  _globals['_ANSWER']._serialized_start=247
  _globals['_ANSWER']._serialized_end=542
  _globals['_ANSWER_METADATAENTRY']._serialized_start=495
  _globals['_ANSWER_METADATAENTRY']._serialized_end=542
  _globals['_RANGE']._serialized_start=544
  _globals['_RANGE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
